### ISSUE TITLE
공격

### ISSUE THREAD

**Issue by disjukr** [lindenbark/p0#4]
구현해야 하는 액션

- `attack` - 캐릭터가 공격모션을 하도록 만들 뿐 실제로 다른 캐릭터의 체력을 닳게 만드는 액션이 아님.
- `hit` - 서버에서만 발생시킬 수 있는 액션. `attack` 액션이 오면 일정 시간 뒤에 충돌판정 후 `hit` 액션 발생.
- `die` - 서버에서만 발생시킬 수 있는 액션.

**Comment by gidongkwon** [comment]
추가적으로 구현해야 하는 기능
- 공격 범위 표시
- 쿨타임
